const { tmpdir } = require('node:os');
const { join } = require('node:path');
const { chromium } = require('playwright');
(async () => {
 const browser = await chromium.launch({ channel: 'chrome', headless: true });
 const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
 const errors = [];
 page.setDefaultTimeout(10000);
 page.on('pageerror', e => { errors.push(e.message); console.log('PAGE ERROR', e.message); });
 page.on('console', m => { if(m.type() === 'error' || m.type() === 'warning') console.log(m.type(),m.text()); });
 await page.goto(process.env.BASE_URL || 'http://localhost:5173');
 await page.waitForSelector('.widget');
 await page.evaluate(() => document.fonts.ready);
 await page.waitForTimeout(500);
 await page.screenshot({ path: join(tmpdir(), 'konj-desktop.png'), fullPage: true });
 console.log('widgets',await page.locator('.widget').count());
 await page.getByRole('textbox', { name: 'کار تازه', exact: true }).fill('تست کار روزانه');
 await page.getByRole('button', { name: 'افزودن کار', exact: true }).click();
 await page.getByRole('checkbox', { name: 'تست کار روزانه' }).check();
 await page.getByRole('textbox', { name: 'یادداشت کوچک', exact: true }).fill('یادداشت ماندگار');
 await page.reload();
 await page.waitForSelector('.widget');
 if (!await page.getByRole('checkbox', { name: 'تست کار روزانه' }).isChecked()) throw Error('Task persistence failed');
 if (await page.getByRole('textbox', { name: 'یادداشت کوچک', exact: true }).inputValue() !== 'یادداشت ماندگار') throw Error('Note persistence failed');
 await page.getByRole('button', { name: 'افزودن ابزارک', exact: true }).click();
 await page.locator('.catalog-item').filter({ hasText: 'جستجو' }).getByRole('button').click();
 await page.locator('dialog').getByRole('button', { name: 'بستن', exact: true }).click();
 if(await page.locator('.widget').count() !== 6) throw Error('Add failed');
 await page.getByRole('button', { name: 'چیدمان', exact: true }).click();
 await page.getByRole('button', { name: 'حذف جستجو', exact: true }).click();
 await page.getByRole('button', { name: 'بازگردانی', exact: true }).click();
 if(await page.locator('.widget').count() !== 6) throw Error('Undo failed');

 const before = await page.evaluate(() => JSON.parse(localStorage.getItem('konj-state')).data.instances);
 const handle = page.locator('.widget-clock .drag-handle');
 const box = await handle.boundingBox();
 await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
 await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 - 420, box.y + box.height / 2 + 105, { steps: 20 }); await page.mouse.up();
 await page.waitForTimeout(400);
 const after = await page.evaluate(() => JSON.parse(localStorage.getItem('konj-state')).data.instances);
 if (JSON.stringify(before.map(w => w.position)) === JSON.stringify(after.map(w => w.position))) throw Error('Drag did not change saved positions');
 await page.locator('.widget-clock .resize-handle').evaluate(el => el.scrollIntoView({ block: 'center' }));
 await page.waitForTimeout(300);
 const resizer = await page.locator('.widget-clock .resize-handle').boundingBox();
 const oldHeight = after.find(w => w.type === 'clock').position.h;
 await page.mouse.move(resizer.x + 5, resizer.y + 5); await page.mouse.down();
 await page.mouse.move(resizer.x + 5, resizer.y + 115, { steps: 12 }); await page.mouse.up();
 await page.waitForTimeout(400);
 const resized = await page.evaluate(() => JSON.parse(localStorage.getItem('konj-state')).data.instances);
 await page.screenshot({ path: join(tmpdir(), 'konj-resize.png'), fullPage: true });
 if(resized.find(w => w.type === 'clock').position.h === oldHeight) throw Error('Resize did not persist');
 await page.reload(); await page.waitForSelector('.widget');
 const reloaded = await page.evaluate(() => JSON.parse(localStorage.getItem('konj-state')).data.instances);
 if(JSON.stringify(resized) !== JSON.stringify(reloaded)) throw Error('Layout changed after reload');
 await page.getByRole('button', { name: 'افزودن', exact: true }).click();
 await page.getByRole('textbox', { name: 'نام سایت', exact: true }).fill('آزمایش');
 await page.getByRole('textbox', { name: 'آدرس سایت', exact: true }).fill('https://example.com');
 await page.getByRole('button', { name: 'ذخیره', exact: true }).click();
 if(await page.getByRole('link', { name: 'آزمایش' }).getAttribute('href') !== 'https://example.com/') throw Error('Shortcut failed');
 await page.getByRole('button', { name: 'چیدمان', exact: true }).click();
 await page.getByRole('button', { name: 'انتقال به بعد', exact: true }).first().click();
 await page.waitForTimeout(300);
 await page.getByRole('button', { name: 'پایان ویرایش', exact: true }).click();
 await page.getByRole('button', { name: 'تنظیمات', exact: true }).click();
 await page.getByRole('textbox', { name: 'چه صدایت کنیم؟' }).fill('سارا');
 await page.getByRole('radio', { name: 'مهِ جنگل' }).check();
 await page.getByRole('checkbox', { name: 'شفافیت کمتر' }).check();
 await page.keyboard.press('Escape');
 await page.reload();
 await page.waitForSelector('.app-shell[data-theme="forest"].opaque');
 if(!await page.getByRole('heading', { level: 1 }).textContent().then(s => s.includes('سارا'))) throw Error('Name persistence failed');
 await page.setViewportSize({ width: 390, height: 844 });
 await page.waitForTimeout(500);
 await page.screenshot({ path: join(tmpdir(), 'konj-mobile.png'), fullPage: true });
 if(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth || [...document.querySelectorAll('.widget')].some(el => { const r = el.getBoundingClientRect(); return r.left < 0 || r.right > innerWidth; }))) throw Error('Mobile overflow');
 await page.getByRole('button', { name: 'چیدمان', exact: true }).click();
 while(await page.locator('.widget-actions .danger').count()) await page.locator('.widget-actions .danger').first().click();
 await page.reload();
 await page.waitForSelector('.empty-dashboard');
 if(await page.locator('.widget').count() !== 0) throw Error('Empty dashboard persistence failed');
 if(errors.length) throw Error(errors.join('\n'));
 console.log('PASS: rendering, tasks, notes, add/remove/undo, drag/resize, keyboard ordering, shortcuts, preferences, mobile, empty persistence; no browser errors');
 await browser.close();
})().catch(e => { console.error(e); process.exit(1) });
