<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useWidgetsStore } from '@/stores/widgets'
import type { WidgetInstance } from '@/types/widget'
const props = defineProps<{ widget: WidgetInstance }>()
const { t, locale } = useI18n()
const store = useWidgetsStore()
interface City { id: number; name: string; country?: string; admin1?: string; latitude: number; longitude: number }
interface Weather { temperature: number; code: number; wind: number; updated: number }
const city = computed(() => props.widget.settings.city as City | undefined)
const weather = ref<Weather>()
const query = ref(''); const results = ref<City[]>([]); const loading = ref(false); const error = ref(''); const searching = ref(!city.value)
let controller: AbortController | undefined
let refresh: ReturnType<typeof setInterval> | undefined
async function request(url: string) { controller?.abort(); const active = new AbortController(); controller = active; const timeout = setTimeout(() => active.abort(), 12000); try { const response = await fetch(url, { signal: active.signal }); if (!response.ok) throw Error('Weather unavailable'); return await response.json() } finally { clearTimeout(timeout) } }
async function search() { if (query.value.trim().length < 2 || loading.value) return; loading.value = true; error.value = ''; results.value = []; try { const data = await request(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query.value.trim())}&count=5&language=${locale.value}&format=json`); results.value = (data.results || []).filter((c: City) => Number.isFinite(c.latitude) && Number.isFinite(c.longitude)); if (!results.value.length) error.value = 'extras.noCities' } catch { error.value = 'extras.weatherError' } finally { loading.value = false } }
async function load() { if (!city.value || loading.value) return; loading.value = true; error.value = ''; try { const data = await request(`https://api.open-meteo.com/v1/forecast?latitude=${city.value.latitude}&longitude=${city.value.longitude}&current=temperature_2m,weather_code,wind_speed_10m&timezone=auto`); const c = data.current; if (![c?.temperature_2m, c?.weather_code, c?.wind_speed_10m].every(Number.isFinite)) throw Error('Invalid weather'); weather.value = { temperature: c.temperature_2m, code: c.weather_code, wind: c.wind_speed_10m, updated: Date.now() } } catch { error.value = 'extras.weatherError' } finally { loading.value = false } }
function choose(value: City) { store.updateSettings(props.widget.id, { city: value }); searching.value = false; results.value = []; weather.value = undefined; void load() }
const condition = computed(() => { const c = weather.value?.code ?? -1; return c === 0 ? 'clear' : c <= 3 && c > 0 ? 'cloudy' : [45,48].includes(c) ? 'fog' : [71,73,75,77,85,86].includes(c) ? 'snow' : c >= 95 ? 'storm' : c >= 51 ? 'rainy' : 'unknownWeather' })
onMounted(() => { void load(); refresh = setInterval(() => { if (!searching.value) void load() }, 15 * 60 * 1000) })
onUnmounted(() => { controller?.abort(); clearInterval(refresh) })
</script>
<template><div class="extra-widget weather-content"><form v-if="searching" class="widget-form" @submit.prevent="search"><label>{{ t('extras.city') }}<input v-model="query" required minlength="2" maxlength="100" :placeholder="t('extras.cityPlaceholder')" /></label><button class="secondary-button" :disabled="loading">{{ t('search.submit') }}</button><small class="widget-muted">{{ t('extras.weatherPrivacy') }}</small><button v-for="result in results" :key="result.id" type="button" class="city-result secondary-button" @click="choose(result)">{{ [result.name, result.admin1, result.country].filter(Boolean).join(', ') }}</button><button v-if="city" type="button" class="text-button" @click="searching = false">{{ t('common.cancel') }}</button></form><template v-else><strong dir="auto">{{ city?.name }}</strong><template v-if="weather"><div class="widget-number">{{ Math.round(weather.temperature).toLocaleString(locale) }}°<small>C</small></div><p>{{ t(`extras.${condition}`) }}</p><small class="widget-muted">{{ t('extras.wind', { speed: weather.wind.toLocaleString(locale) }) }}</small><small class="widget-muted">{{ t('extras.updated', { time: new Intl.DateTimeFormat(locale, { hour: '2-digit', minute: '2-digit' }).format(weather.updated) }) }}</small></template><div class="widget-controls"><button class="text-button" :disabled="loading" @click="load">{{ t('extras.refresh') }}</button><button class="text-button" :disabled="loading" @click="searching = true; error = ''">{{ t('extras.changeCity') }}</button></div></template><p v-if="loading" class="widget-muted" role="status">{{ t('extras.loading') }}</p><p v-if="error" class="widget-muted" role="alert">{{ t(error) }}</p><a class="weather-credit" href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">{{ t('extras.weatherCredit') }}</a></div></template>
